
typedef enum COLOR_T {
    DEFAULT_COLOR=0,
    INPUT_COLOR=1,
    ECHO_COLOR=2,
    ERROR_COLOR=3,
    WARNING_COLOR=4,
    GLOBAL_COLOR=5,
    ADMIN_COLOR=6,
    HIGHLIGHT_COLOR=7,
    BACKGROUND_COLOR=8,
    NUM_COLORTYPES=9
} COLOR_T;


#define CGUnit_C void;
#define CGPlayer_C void;