#pragma once

#define ENTITY_MANAGER_PTR 0xB41414
#define FIRST_ENTITY   	   0xAC
#define NEXT_ENTITY        0x3C
#define ENTITY_TYPE	       0x14

#define CONSOLEWRITE_FUN_PTR     0x63CB50
#define CONSOLESETHOTKEY_FUN_PTR 0x63CB00
#define CONSOLECOMMANDREGISTER_FUN_PTR 0x63F9E0
